Euler:
	g++ -std=c++11  -fsanitize=address -fsanitize=leak -fsanitize=undefined  Euler.cpp
Euler2:
	g++ -std=c++11  -fsanitize=address -fsanitize=leak -fsanitize=undefined  Euler2.cpp
lorentz:
	g++ -std=c++11 -fsanitize=address -fsanitize=leak -fsanitize=undefined  lorentz.cpp
homework:
	g++ -std=c++11 -fsanitize=address -fsanitize=leak -fsanitize=undefined  Euler_homework.cpp
class1:
	g++ -std=c++11 -fsanitize=address -fsanitize=leak -fsanitize=undefined euler-V2-vector.cpp
class2:
	g++ -std=c++11 -fsanitize=address -fsanitize=leak -fsanitize=undefined runge_kutta.cpp
clean:
	rm -f  *.dat *.txt *.log *.out
