Euler:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  Euler.cpp
Euler2:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  Euler2.cpp
lorentz:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  lorentz.cpp
homework:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  Euler_homework.cpp
clean:
	rm -f *.dat *.txt *.log
