CXX = g++
CXXFLAGS = -std=c++11  -fsanitize=address -fsanitize=leak -fsanitize=undefined 

Euler:
	$(CXX) $(CXXFLAGS) Euler.cpp
Euler2:
	 $(CXX) $(CXXFLAGS)  Euler2.cpp
lorentz:
	 $(CXX) $(CXXFLAGS)  lorentz.cpp
lorentz2:
	 $(CXX) $(CXXFLAGS)  lorentz_rk4.cpp
homework:
	 $(CXX) $(CXXFLAGS)  Euler_homework.cpp
class1:
	$(CXX) $(CXXFLAGS)  euler-V2-vector.cpp
class2:
	$(CXX) $(CXXFLAGS) runge_kutta.cpp
clean:
	rm -f  *.dat *.txt *.log *.out
